import { reviewUrl } from "../platform.ts";
import type { DevAgentConfig } from "../config.ts";
import type { VcsAccountPublishResult } from "../types.ts";
import type { VcsProvider, VcsPublishInput, VcsPublishResult } from "./types.ts";
import {
  advanceAccountRotation,
  orderedAccountsRoundRobin,
} from "./account-rotation.ts";

type GitHubAccount = DevAgentConfig["vcs"]["accounts"][number];

function run(
  cwd: string,
  args: string[],
  env?: Record<string, string>,
): { ok: boolean; out: string } {
  const proc = Bun.spawnSync(args, {
    cwd,
    stdout: "pipe",
    stderr: "pipe",
    env: env ? { ...process.env, ...env } : process.env,
  });
  const stdout = new TextDecoder().decode(proc.stdout).trim();
  const stderr = new TextDecoder().decode(proc.stderr).trim();
  return { ok: proc.exitCode === 0, out: stdout || stderr };
}

function commandExists(cwd: string, name: string): boolean {
  return run(cwd, ["sh", "-c", `command -v ${name}`]).ok;
}

function issueNumberFromUrl(issueUrl: string): string | undefined {
  const m = issueUrl.match(/\/issues\/(\d+)\b/i);
  return m?.[1];
}

function markdownBody(input: VcsPublishInput, issueUrl?: string): string {
  const changes = input.plan.changes
    .map((c) => `- \`${c.file}\`: ${c.description}`)
    .join("\n");
  const num = issueUrl ? issueNumberFromUrl(issueUrl) : undefined;
  const issue = issueUrl
    ? num
      ? `\n\nCloses #${num}\n\nRelated issue: ${issueUrl}`
      : `\n\nRelated issue: ${issueUrl}`
    : "";
  return `## Summary
${input.plan.motivation}

## Changes
${changes}

## Validation
${input.plan.validation}

## Risks
${input.plan.risks.map((r) => `- ${r}`).join("\n") || "- None"}
${issue}

Generated by P7 from commit ${input.commitSha}.`;
}

function firstUrl(text: string): string | undefined {
  return text.match(/https?:\/\/\S+/)?.[0];
}

function envForAccount(account: GitHubAccount): Record<string, string> | undefined {
  if (account.auth_type !== "token_env") return undefined;
  if (!account.token_env) return undefined;
  const token = process.env[account.token_env];
  if (!token) return undefined;
  return {
    GH_TOKEN: token,
    GH_HOST: account.gh_host,
  };
}

function accountEnabled(
  account: GitHubAccount,
  field: "create_issue" | "create_pr" | "auto_merge",
  cfg: DevAgentConfig["vcs"],
): boolean {
  return account[field] ?? cfg[field];
}

function labelsForAccount(account: GitHubAccount, cfg: DevAgentConfig["vcs"]): string[] {
  return account.labels ?? cfg.labels;
}

function reviewersForAccount(account: GitHubAccount, cfg: DevAgentConfig["vcs"]): string[] {
  return account.reviewers ?? cfg.reviewers;
}

function branchForAccount(baseBranch: string, account: GitHubAccount, multiAccount: boolean): string {
  if (!multiAccount) return baseBranch;
  const safeId = account.id.toLowerCase().replace(/[^a-z0-9._-]+/g, "-").replace(/^-+|-+$/g, "");
  return `${baseBranch}-${safeId || "account"}`;
}

function findOpenPrUrl(
  projectPath: string,
  branch: string,
  env?: Record<string, string>,
): string | undefined {
  const r = run(
    projectPath,
    ["gh", "pr", "list", "--head", branch, "--state", "open", "--json", "url", "--limit", "1"],
    env,
  );
  if (!r.ok) return undefined;
  try {
    const rows = JSON.parse(r.out) as Array<{ url: string }>;
    return rows[0]?.url;
  } catch {
    return undefined;
  }
}

export class GitHubProvider implements VcsProvider {
  canHandle(remoteUrl: string | null): boolean {
    return Boolean(remoteUrl?.includes("github.com"));
  }

  async publish(input: VcsPublishInput): Promise<VcsPublishResult> {
    const fallbackUrl = reviewUrl(input.remoteUrl, input.branch);
    const cfg = input.config.vcs;
    if (!cfg.enabled) {
      return { reviewUrl: fallbackUrl, mergeStatus: "skipped" };
    }
    if (!this.canHandle(input.remoteUrl)) {
      return { reviewUrl: fallbackUrl, mergeStatus: "skipped" };
    }
    if (!commandExists(input.projectPath, "gh")) {
      return {
        reviewUrl: fallbackUrl,
        mergeStatus: "skipped",
        warning: "gh CLI not found; returning compare URL only",
      };
    }

    const accounts =
      cfg.accounts.length > 0
        ? cfg.accounts
        : [
            {
              id: "default-gh",
              provider: "github" as const,
              auth_type: "gh" as const,
              gh_host: "github.com",
            },
          ];

    const accountResults: VcsAccountPublishResult[] = [];
    const pickAll = cfg.account_pick_mode === "all";

    if (pickAll) {
      for (const account of accounts) {
        accountResults.push(await this.publishWithAccount(input, account, accounts.length > 1));
      }
    } else {
      const { order } = orderedAccountsRoundRobin(accounts, input.projectPath);
      const tryOrder = order.length > 0 ? order : accounts;
      let winner: VcsAccountPublishResult | null = null;
      for (const account of tryOrder) {
        const result = await this.publishWithAccount(input, account, false);
        accountResults.push(result);
        if (result.ok) {
          winner = result;
          break;
        }
        if (cfg.account_failover === false) break;
      }
      if (winner?.ok) {
        advanceAccountRotation(input.projectPath, winner.accountId, accounts);
      }
    }

    const firstPr = accountResults.find((r) => r.prUrl);
    const firstIssue = accountResults.find((r) => r.issueUrl);
    const ok = accountResults.some((r) => r.ok);
    const mergeStatus = accountResults.some((r) => r.mergeStatus === "queued")
      ? "queued"
      : accountResults.some((r) => r.mergeStatus === "merged")
        ? "merged"
        : ok
          ? "not_requested"
          : "failed";

    return {
      reviewUrl: fallbackUrl,
      prUrl: firstPr?.prUrl,
      issueUrl: firstIssue?.issueUrl,
      mergeStatus,
      accountResults,
      warning: ok
        ? accountResults.filter((r) => !r.ok).map((r) => `${r.accountId}: ${r.warning}`).join("; ") || undefined
        : accountResults.map((r) => `${r.accountId}: ${r.warning}`).join("; "),
    };
  }

  private async publishWithAccount(
    input: VcsPublishInput,
    account: GitHubAccount,
    multiAccount: boolean,
  ): Promise<VcsAccountPublishResult> {
    const cfg = input.config.vcs;
    const env = envForAccount(account);
    const branch = branchForAccount(input.branch, account, multiAccount);
    if (account.auth_type === "token_env" && !env?.GH_TOKEN) {
      return {
        accountId: account.id,
        ok: false,
        branch,
        mergeStatus: "skipped",
        warning: `missing token env ${account.token_env ?? "(unset)"}`,
      };
    }

    if (account.auth_type === "gh") {
      const auth = run(input.projectPath, ["gh", "auth", "status", "--hostname", account.gh_host], env);
      if (!auth.ok) {
        return {
          accountId: account.id,
          ok: false,
          branch,
          mergeStatus: "skipped",
          warning: `gh CLI is not authenticated for ${account.gh_host}`,
        };
      }
    }

    let issueUrl: string | undefined;
    if (accountEnabled(account, "create_issue", cfg)) {
      const issueArgs = [
        "gh",
        "issue",
        "create",
        "--title",
        input.plan.title,
        "--body",
        input.plan.motivation,
      ];
      const labels = labelsForAccount(account, cfg);
      if (labels.length > 0) issueArgs.push("--label", labels.join(","));
      const issue = run(input.projectPath, issueArgs, env);
      if (issue.ok) issueUrl = firstUrl(issue.out) ?? issue.out;
    }

    if (!accountEnabled(account, "create_pr", cfg)) {
      return {
        accountId: account.id,
        ok: Boolean(issueUrl),
        branch,
        issueUrl,
        mergeStatus: "skipped",
      };
    }

    const existingPr = findOpenPrUrl(input.projectPath, branch, env);
    if (existingPr) {
      return {
        accountId: account.id,
        ok: true,
        branch,
        prUrl: existingPr,
        issueUrl,
        mergeStatus: "not_requested",
      };
    }

    if (branch !== input.branch) {
      const push = run(input.projectPath, ["git", "push", "origin", `HEAD:${branch}`], env);
      if (!push.ok) {
        return {
          accountId: account.id,
          ok: false,
          branch,
          issueUrl,
          mergeStatus: "failed",
          warning: `git push account branch failed: ${push.out}`,
        };
      }
    }

    const prArgs = [
      "gh",
      "pr",
      "create",
      "--title",
      input.plan.title,
      "--body",
      markdownBody(input, issueUrl),
      "--head",
      branch,
    ];
    if (cfg.base_branch) prArgs.push("--base", cfg.base_branch);
    for (const reviewer of reviewersForAccount(account, cfg)) {
      prArgs.push("--reviewer", reviewer);
    }

    const pr = run(input.projectPath, prArgs, env);
    if (!pr.ok) {
      return {
        accountId: account.id,
        ok: false,
        branch,
        issueUrl,
        mergeStatus: "failed",
        warning: `gh pr create failed: ${pr.out}`,
      };
    }

    const prUrl = firstUrl(pr.out) ?? pr.out;
    // 合并与 review 由 executor 内 runPrReviewAndMerge 统一处理（含冲突修复）
    const mergeStatus: VcsPublishResult["mergeStatus"] = "not_requested";

    return {
      accountId: account.id,
      ok: true,
      branch,
      prUrl,
      issueUrl,
      mergeStatus,
    };
  }
}
